### ISSUE TITLE
inching support

### ISSUE THREAD

**Issue by matthieut59** [mattsaxon/sonoff-lan-mode-homeassistant#50]
Hello,

first awsome work! I changed a bit the component to activate inching, but not that simple as expected, HA seems to be lost and switch start blinking in loop :)

Any chance you can activate this support ?
Indeed I m using the switch to control the pool pump, and even if I m turning on and off the pump with your component, I would like to use long inching in case I lose completly HA, so that at some point the pump should turn off by itself :)

thks in advance!

Matt

**Comment by mattsaxon** [comment]
I'm stopping maintaining this component, instead I'd recommend using https://github.com/AlexxIT/SonoffLAN . It much more functional and reliable, so any contributions I make in future will be to that repo. I suggest you try that component first and if there are issues, raise an issue/feature request there.

However one thing to be aware of it that inching should work if it is configured via eWeLink, even if connectivity is lost. It is the switch that has the inching functionality in it, so this component should work without using its inching functionality, I use it that way myself and was thinking about removing the faulty inching functionality rather than fixing it

**Comment by matthieut59** [comment]
Fine for me!
As I m sure I won t be alone reaching your fork, any chance you update your readme so that we can easily reach alexxIT fork ?

**Comment by mattsaxon** [comment]
Yep, the readme is already updated.
